### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by jfbookingbug** [taiadt/bbugrep#2]
pls add a simple read me that a non java user can use to run your program :) thanks!

**Comment by jfbookingbug** [comment]
preferably we want this to run on a command line without the use of an IME

**Comment by taiadt** [comment]
Sorry for this delay, I have changed project using maven.
Please use this link to acces the project. [https://github.com/taiadt/maven-first-test]

**Comment by jfbookingbug** [comment]
![image](https://user-images.githubusercontent.com/13979377/34102387-dbf62f32-e3e0-11e7-9ecb-defc626d7339.png)
:)
